#!/bin/sh /etc/rc.common

START=95
STOP=01
USE_PROCD=1

PROG=/usr/bin/giwifi-auto
CONFIG=/etc/config/giwifi-auto
SERVICE=giwifi-auto

start_service() {
	[ -x "$PROG" ] || return 1
	[ -r "$CONFIG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" daemon --config "$CONFIG"
	procd_set_param file "$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 10
	procd_close_instance
}

reload_service() {
	procd_send_signal "$SERVICE" "*" HUP
}

service_triggers() {
	procd_add_reload_trigger giwifi-auto
}
